FROM node:14.16-alpine

WORKDIR "/app"

RUN apk --no-cache add --virtual builds-deps build-base python
COPY ./package.json ./
RUN yarn
RUN yarn global add pm2

COPY . .

CMD ["pm2-runtime", "start", "ecosystem.config.js"]
# CMD ["npm", "run", "dev"]